### ISSUE TITLE
git submodule配置问题

### ISSUE THREAD

**Issue by mayerui** [Gusabary/UNO#1]
![image](https://user-images.githubusercontent.com/25812837/107947709-ba545580-6fcd-11eb-8f33-bc29ac908672.png)
在执行UNO/scripts/build.sh时提示
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

在配置好github的sshkey后,问题解决。 建议在README中加一些提示。

**Comment by Gusabary** [comment]
已添加，感谢分享
（关于配置 github sshkey 的参考：https://www.cnblogs.com/chuyanfenfei/p/8035067.html）
