### ISSUE TITLE
无法启动游戏

### ISSUE THREAD

**Issue by mooneclipsed** [Gusabary/UNO#3]
`$ ./uno -c 8.133.165.59:20040 -u u1`
`$ oops, server has shutdown`
测试了很多端口号还是不行
系统是macos big sur 11.2.3。

**Comment by Gusabary** [comment]
很抱歉，由于预算问题，位于 `8.133.165.59` 上的预启动游戏服务已经停止运行，不过玩家仍可以[启动自己的游戏服务](https://github.com/Gusabary/UNO#%E5%90%AF%E5%8A%A8%E8%87%AA%E5%B7%B1%E7%9A%84%E6%B8%B8%E6%88%8F%E6%9C%8D%E5%8A%A1)。
感谢对本项目的支持。

**Comment by mooneclipsed** [comment]
感谢回复，我是大三，想学习一下c++的网络库，恰巧看到了，打算学习一下。

**Comment by FierceJDM** [comment]
> 很抱歉，由于预算问题，位于 `8.133.165.59` 上的预启动游戏服务已经停止运行，不过玩家仍可以[启动自己的游戏服务](https://github.com/Gusabary/UNO#%E5%90%AF%E5%8A%A8%E8%87%AA%E5%B7%B1%E7%9A%84%E6%B8%B8%E6%88%8F%E6%9C%8D%E5%8A%A1)。 感谢对本项目的支持。

(Answering after translating this) How do you start your own server ?

**Comment by Gusabary** [comment]
@FierceJDM you can check this in readme: https://github.com/Gusabary/UNO/blob/master/README.en.md#start-your-first-game
